### ISSUE TITLE
Deprecated context -> cookbook should declare `unified_mode true` at 1 location:

### ISSUE THREAD

**Issue by hightrek** [chef-cookbooks/auditd#67]
Hi Team,

We have updated on last version Chef-client 17.0.242-1 and  we have this issue after running.

Deprecated features used!
  The auditd_builtins resource in the auditd cookbook should declare `unified_mode true` at 1 location:
    - /opt/chef/embedded/lib/ruby/3.0.0/forwardable.rb:238:in `setup_run_context'
   See https://docs.chef.io/deprecations_unified_mode/ for further details.
  The auditd_conf_file resource in the auditd cookbook should declare `unified_mode true` at 1 location:
    - /opt/chef/embedded/lib/ruby/3.0.0/forwardable.rb:238:in `setup_run_context'
   See https://docs.chef.io/deprecations_unified_mode/ for further details.
  The auditd_ruleset resource in the auditd cookbook should declare `unified_mode true` at 1 location:
    - /opt/chef/embedded/lib/ruby/3.0.0/forwardable.rb:238:in `setup_run_context'
   See https://docs.chef.io/deprecations_unified_mode/ for further details.

It's resources files...

If you have any information for fix this issue.

Thanks a lot.

HT

**Comment by BhanupriyaH** [comment]
Hi, am stuck with same issue on upgrading chef from 16.x to 17.0.242. Auditd cookbook version - 2.3.4
@hightrek since its been a while you raised this issue were you able to resolve on your environment? 
Any help appreciated. Thanks in advance.
